pipeline {
    agent any
    stages {
         stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Test') {
            steps {
                bat 'mvn clean test -Dtest=PipelineTest/AllureReport/demo'

            }
        }
    }
}
