pipeline {
    agent any
    stages {
         stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Test') {
		step{
			bat 'mvn -f C:\ProgramData\Jenkins\.jenkins\workspace\PipelineTest\AllureReport\demo'
		}
            steps {
                bat 'mvn clean test'

            }
        }
    }
}
